export enum CampState {
  auNSW = "auNSW",
  auVIC = "auVIC",
  auQLD = "auQLD",
  auSA = "auSA",
  auTAS = "auTAS",
  auACT = "auACT",
  auNT = "auNT",
  auWA = "auWA",
  usAK = "usAK",
  usAZ = "usAZ",
  usCA = "usCA",
  usFL = "usFL",
  usGA = "usGA",
  usHI = "usHI",
  usID = "usID",
  usIL = "usIL",
  usIN = "usIN",
  usIA = "usIA",
  usKY = "usKY",
  usLA = "usLA",
  usMD = "usMD",
  usMI = "usMI",
  usMN = "usMN",
  usMO = "usMO",
  usMS = "usMS",
  usMT = "usMT",
  usNC = "usNC",
  usND = "usND",
  usNE = "usNE",
  usNH = "usNH",
  usNJ = "usNJ",
  usNM = "usNM",
  usNV = "usNV",
  usNY = "usNY",
  usOH = "usOH",
  usOK = "usOK",
  usOR = "usOR",
  usPA = "usPA",
  usRI = "usRI",
  usSC = "usSC",
  usSD = "usSD",
  usTN = "usTN",
  usTX = "usTX",
  usUT = "usUT",
  usVA = "usVA",
  usWA = "usWA",
  usWV = "usWV",
  usWI = "usWI",
  usWY = "usWY",
}

export const campStateDisplayName: Record<CampState, string> = {
  [CampState.auNSW]: "New South Wales",
  [CampState.auVIC]: "Victoria",
  [CampState.auQLD]: "Queensland",
  [CampState.auSA]: "South Australia",
  [CampState.auTAS]: "Tasmania",
  [CampState.auACT]: "Australian Capital Territory",
  [CampState.auNT]: "Northern Territory",
  [CampState.auWA]: "Western Australia",
  [CampState.usAK]: "Alaska",
  [CampState.usAZ]: "Arizona",
  [CampState.usCA]: "California",
  [CampState.usFL]: "Florida",
  [CampState.usGA]: "Georgia",
  [CampState.usHI]: "Hawaii",
  [CampState.usID]: "Idaho",
  [CampState.usIL]: "Illinois",
  [CampState.usIN]: "Indiana",
  [CampState.usIA]: "Iowa",
  [CampState.usKY]: "Kentucky",
  [CampState.usLA]: "Louisiana",
  [CampState.usMD]: "Maryland",
  [CampState.usMI]: "Michigan",
  [CampState.usMN]: "Minnesota",
  [CampState.usMO]: "Missouri",
  [CampState.usMS]: "Mississippi",
  [CampState.usMT]: "Montana",
  [CampState.usNC]: "North Carolina",
  [CampState.usND]: "North Dakota",
  [CampState.usNE]: "Nebraska",
  [CampState.usNH]: "New Hampshire",
  [CampState.usNJ]: "New Jersey",
  [CampState.usNM]: "New Mexico",
  [CampState.usNV]: "Nevada",
  [CampState.usNY]: "New York",
  [CampState.usOH]: "Ohio",
  [CampState.usOK]: "Oklahoma",
  [CampState.usOR]: "Oregon",
  [CampState.usPA]: "Pennsylvania",
  [CampState.usRI]: "Rhode Island",
  [CampState.usSC]: "South Carolina",
  [CampState.usSD]: "South Dakota",
  [CampState.usTN]: "Tennessee",
  [CampState.usTX]: "Texas",
  [CampState.usUT]: "Utah",
  [CampState.usVA]: "Virginia",
  [CampState.usWA]: "Washington",
  [CampState.usWV]: "West Virginia",
  [CampState.usWI]: "Wisconsin",
  [CampState.usWY]: "Wyoming",
};

export function isSameCountry(state1: CampState, state2: CampState) {
  return state1[0] === state2[0] && state1[1] === state2[1];
}
