name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-firebase-functions.yml'
      - 'functions/**'

concurrency:
  group: firebase-functions
  cancel-in-progress: true

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          # Note: these are not secrets
          service_account: "github@backdrop-studio.iam.gserviceaccount.com"
          workload_identity_provider: "projects/692475653554/locations/global/workloadIdentityPools/github/providers/github-repo"
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      - run: |
          pushd functions/shared
          npm install
          npm run build
          popd
      - run: |
          pushd functions
          npm install
          npm run deploy || (sleep 30 && npm run deploy)
          popd
