name: Deploy Firestore Rules
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-firestore-rules.yml
      - firestore.rules

concurrency:
  group: firebase-rules
  cancel-in-progress: true

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          # Note: these are not secrets
          service_account: "github@tgbc-camp-tickets.iam.gserviceaccount.com"
          workload_identity_provider: "projects/785909138910/locations/global/workloadIdentityPools/github/providers/github-repo"
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      - run: npm install
      - run: npm run deploy:firestore:rules
